In [99]:
import csv
import numpy as np
import keras as kr

#load the Iris dataset
iris = list(csv.reader(open("IRIS.csv")))[1:]

print(*iris, sep='\n')



['5.1', '3.5', '1.4', '0.2', 'setosa']
['4.9', '3.0', '1.4', '0.2', 'setosa']
['4.7', '3.2', '1.3', '0.2', 'setosa']
['4.6', '3.1', '1.5', '0.2', 'setosa']
['5.0', '3.6', '1.4', '0.2', 'setosa']
['5.4', '3.9', '1.7', '0.4', 'setosa']
['4.6', '3.4', '1.4', '0.3', 'setosa']
['5.0', '3.4', '1.5', '0.2', 'setosa']
['4.4', '2.9', '1.4', '0.2', 'setosa']
['4.9', '3.1', '1.5', '0.1', 'setosa']
['5.4', '3.7', '1.5', '0.2', 'setosa']
['4.8', '3.4', '1.6', '0.2', 'setosa']
['4.8', '3.0', '1.4', '0.1', 'setosa']
['4.3', '3.0', '1.1', '0.1', 'setosa']
['5.8', '4.0', '1.2', '0.2', 'setosa']
['5.7', '4.4', '1.5', '0.4', 'setosa']
['5.4', '3.9', '1.3', '0.4', 'setosa']
['5.1', '3.5', '1.4', '0.3', 'setosa']
['5.7', '3.8', '1.7', '0.3', 'setosa']
['5.1', '3.8', '1.5', '0.3', 'setosa']
['5.4', '3.4', '1.7', '0.2', 'setosa']
['5.1', '3.7', '1.5', '0.4', 'setosa']
['4.6', '3.6', '1.0', '0.2', 'setosa']
['5.1', '3.3', '1.7', '0.5', 'setosa']
['4.8', '3.4', '1.9', '0.2', 'setosa']
['5.0', '3.0', '1.6', '0.

In [100]:
inputs = np.array(iris)[:,:4].astype(np.float)
print (inputs)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [101]:
# 4 inputs sepal length & width, petal length & width
inputs = np.array(iris)[:,:4].astype(np.float)
print (inputs)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [102]:
# outputs are initially strings , setosa, versicolor, virginica
outputs = np.array(iris)[:,4]
print(outputs)

['setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'v

In [103]:
#convert the out strings to ints
outputs_vals, outputs_inds = np.unique(outputs, return_inverse=True)
print (outputs_vals, sep='/n')

['setosa' 'versicolor' 'virginica']


In [104]:
print (outputs_inds, sep='/n')

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [105]:
# endocde the category integers as binary categorial vairables.
outputs_cats = kr.utils.to_categorical(outputs_inds)
print (output_cats)

[[0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [106]:
print (len(inputs))

150


In [107]:
# split the input & output data sets into training and test subsets
inds = np.random.permutation(len(inputs))
print(inds)

[116 142  31 103 102  46 130 101  49 114   5 143   6  71  68 127  91 135
  32  80   7 122  13 124  26  34  35  89  77  75  51  61 147 104  33 138
 126 129 117 121 136  72  65  36  54  27 134  86  95   2  11 131 125   8
 119  53 106 146  83  88 148  66 108  69  76   0  42   9  79  17  82  45
 120  92 128  84 112 109  16  21  18  98 105  24  59 141  57  30   3  99
  55  63  38  70 145  29  44 144  19  15  37   1  97  60  78  93 133  39
  81 111  74  67 139 118  20  58  23 113  14  12  47  25  96  64  41  22
  90 110  50 140 132  40  10  52  62 115  28 137  85  73 149   4  87 100
  48  94 123 107  56  43]


In [108]:
train_inds, test_inds = np.array_split(inds, 2)
print(train_inds, sep='/n')
print(test_inds, sep='/n')



[116 142  31 103 102  46 130 101  49 114   5 143   6  71  68 127  91 135
  32  80   7 122  13 124  26  34  35  89  77  75  51  61 147 104  33 138
 126 129 117 121 136  72  65  36  54  27 134  86  95   2  11 131 125   8
 119  53 106 146  83  88 148  66 108  69  76   0  42   9  79  17  82  45
 120  92 128]
[ 84 112 109  16  21  18  98 105  24  59 141  57  30   3  99  55  63  38
  70 145  29  44 144  19  15  37   1  97  60  78  93 133  39  81 111  74
  67 139 118  20  58  23 113  14  12  47  25  96  64  41  22  90 110  50
 140 132  40  10  52  62 115  28 137  85  73 149   4  87 100  48  94 123
 107  56  43]


In [109]:

inputs_train, outputs_train = inputs[train_inds], output_cats[train_inds]
inputs_test, outputs_test = inputs[test_inds], output_cats[test_inds]

print(inputs_train, sep='/n')
print('Break for training and test data')
print(inputs_test, sep='/n')



[[6.5 3.  5.5 1.8]
 [5.8 2.7 5.1 1.9]
 [5.4 3.4 1.5 0.4]
 [6.3 2.9 5.6 1.8]
 [7.1 3.  5.9 2.1]
 [5.1 3.8 1.6 0.2]
 [7.4 2.8 6.1 1.9]
 [5.8 2.7 5.1 1.9]
 [5.  3.3 1.4 0.2]
 [5.8 2.8 5.1 2.4]
 [5.4 3.9 1.7 0.4]
 [6.8 3.2 5.9 2.3]
 [4.6 3.4 1.4 0.3]
 [6.1 2.8 4.  1.3]
 [6.2 2.2 4.5 1.5]
 [6.1 3.  4.9 1.8]
 [6.1 3.  4.6 1.4]
 [7.7 3.  6.1 2.3]
 [5.2 4.1 1.5 0.1]
 [5.5 2.4 3.8 1.1]
 [5.  3.4 1.5 0.2]
 [7.7 2.8 6.7 2. ]
 [4.3 3.  1.1 0.1]
 [6.7 3.3 5.7 2.1]
 [5.  3.4 1.6 0.4]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 2.5 4.  1.3]
 [6.7 3.  5.  1.7]
 [6.6 3.  4.4 1.4]
 [6.4 3.2 4.5 1.5]
 [5.9 3.  4.2 1.5]
 [6.5 3.  5.2 2. ]
 [6.5 3.  5.8 2.2]
 [5.5 4.2 1.4 0.2]
 [6.  3.  4.8 1.8]
 [6.2 2.8 4.8 1.8]
 [7.2 3.  5.8 1.6]
 [7.7 3.8 6.7 2.2]
 [5.6 2.8 4.9 2. ]
 [6.3 3.4 5.6 2.4]
 [6.3 2.5 4.9 1.5]
 [6.7 3.1 4.4 1.4]
 [5.5 3.5 1.3 0.2]
 [6.5 2.8 4.6 1.5]
 [5.2 3.5 1.5 0.2]
 [6.1 2.6 5.6 1.4]
 [6.7 3.1 4.7 1.5]
 [5.7 3.  4.2 1.2]
 [4.7 3.2 1.3 0.2]
 [4.8 3.4 1.6 0.2]
 [7.9 3.8 6.4 2. ]
 [7.2 3.2 6.

In [110]:
#creats a neral network
model = kr.models.Sequential()

# add an initial layer with 4 inputs nodes, and a hidden layer with 16 nodes
model.add(kr.layers.Dense(16, input_shape=(4,)))

#appy the signoid activation function to that layer
model.add(kr.layers.Activation("sigmoid"))

#add another layer connected to the layet with 16 nodes containing 3 output nodes
model.add(kr.layers.Dense(3))

#use the softmax activation function there
model.add(kr.layers.Activation("softmax"))

In [111]:

# configure the model for training# confi 
# uses the adam optimizer and categorialcross entropy as the loss function
# add in some extra metrics, accuracy being the only one.
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

#fit the model using our training data
model.fit(inputs_train, outputs_train, epochs=100, batch_size=1, verbose=1)
#evaluate the model using the test data set
loss, accuracy = model.evaluate(inputs_test, outputs_test, verbose=1)


print("\n\nloss: %6.4f\nAccuracy: %6.4f"% (loss, accuracy))

ValueError: Error when checking target: expected activation_29 to have shape (None, 3) but got array with shape (75, 22)